/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g0xx.h"

volatile uint32_t ms_ticks = 0;
volatile uint32_t last_press_time = 0;
volatile uint8_t current_state = 0;

void set_blink_state(uint8_t state);

int main(void)
{
    SysTick_Config(16000);

    RCC->APBENR1 |= RCC_APBENR1_TIM3EN;
    RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
    RCC->IOPENR |= RCC_IOPENR_GPIOCEN;

    GPIOA->MODER &= ~(3<<10);   // clear PA5 mode bits
    GPIOA->MODER |= (1<<10);    // set PA5 to output mode

    GPIOC->MODER &= ~(3<<26);   // clear PC13 mode bits -> input mode

    RCC->APBENR2 |= RCC_APBENR2_SYSCFGEN;
    EXTI->EXTICR[3] &= ~EXTI_EXTICR4_EXTI13_Msk;
    EXTI->EXTICR[3] |= EXTI_EXTICR4_EXTI13;

    EXTI->FTSR1 |= (1<<13);
    EXTI->IMR1 |= (1<<13);

    NVIC_EnableIRQ(EXTI4_15_IRQn);

    TIM3->PSC = 15999;        // one-time: 1ms tick base, regardless of state
    TIM3->DIER |= (1<<0);     // one-time: enable update interrupt
    NVIC_EnableIRQ(TIM3_IRQn);

    set_blink_state(current_state);   // apply initial state (0 = off) -> stops timer, forces LED off

    for(;;)
        __WFI();
}

void set_blink_state(uint8_t state)
{
    switch (state)
    {
    case 0:
        TIM3->CR1 &= ~(1<<0);
        GPIOA->ODR &= ~(0x20);
        break;
    case 1:
        TIM3->CR1 |= (1<<0);
        TIM3->ARR = 999;
        TIM3->CNT = 0;
        break;
    case 2:
        TIM3->CR1 |= (1<<0);
        TIM3->ARR = 499;
        TIM3->CNT = 0;
        break;
    case 3:
        TIM3->CR1 |= (1<<0);
        TIM3->ARR = 249;
        TIM3->CNT = 0;
        break;
    }
}

void TIM3_IRQHandler(void)
{
    if (TIM3->SR & (1<<0))
    {
        GPIOA->ODR ^= 0x20;
    }
    TIM3->SR &= ~(1<<0);
}

void SysTick_Handler(void)
{
    ms_ticks++;
}

void EXTI4_15_IRQHandler(void)
{
    if (EXTI->FPR1 & (1<<13))
    {
        if (ms_ticks - last_press_time > 50)
        {
            current_state++;
            if (current_state % 4 == 0)
            {
                current_state = 0;
            }
            set_blink_state(current_state);
            last_press_time = ms_ticks;
        }
        EXTI->FPR1 |= (1<<13);
    }
}
